### ISSUE TITLE
Broken `go.mod` file (3.4): version tag not corresponding with package name

### ISSUE THREAD

**Issue by bozaro** [etcd-io/etcd#12109]
# Issue
I can't get add to project etcd client 3.4+ without tricks:
```
➜  go get go.etcd.io/etcd@v3.4.9
go get go.etcd.io/etcd@v3.4.9: go.etcd.io/etcd@v3.4.9: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v
```

# Workaround
Add module replace by commit hash instead of tag name:
```
➜  git rev-list -n 1 v3.4.9
54ba9589114fc3fa5cc36c313550b3c0c0938c91
➜  go mod edit -replace go.etcd.io/etcd=github.com/etcd-io/etcd@$(git rev-list -n 1 v3.4.9)
➜  cat go.mod 
module bozaro.ru/example

go 1.14

replace go.etcd.io/etcd => github.com/etcd-io/etcd v0.5.0-alpha.5.0.20200520232829-54ba9589114f
```

# Correct solution (unfortunatelly it is breaking change)

 1. Update package name in `go.mod` by adding `v3` suffix:
   ```
➜  go mod edit -module go.etcd.io/etcd/v3 go.mod
```
 2. Update package name in all `*.go` files:
   ```
➜  find . -type f -name '*.go' -exec sed -i -e 's,go.etcd.io/etcd,go.etcd.io/etcd/v3,g' {} \;
```

# References
 - Golang blog: https://blog.golang.org/v2-go-modules
 - Example of working repository: https://github.com/olivere/elastic/blob/v7.0.17/go.mod

**Comment by ldelossa** [comment]
I also think "get getting" the latest commit hash pulls in the correct code without the need for the replace.

**Comment by ptabor** [comment]
I believe this got fixed in 3.5.x branch: https://github.com/etcd-io/etcd/issues/11820 . 
I think changes of all imports paths is too big change for backporting to a patch release.

**Comment by ptabor** [comment]
Please see https://github.com/etcd-io/etcd/issues/12068#issuecomment-653757627 for summary of the current etcd go.mod situation: 
  https://github.com/etcd-io/etcd/issues/12068#issuecomment-653757627

**Comment by feldgendler** [comment]
Hi! This is half a year old, and v3.5.0 is still not released. Can we hope for either a v3.5.0 release, or a fix on the v3.4.x branch?

**Comment by feldgendler** [comment]
@ptabor Hi! This is half a year old, and v3.5.0 is still not released. Can we hope for either a v3.5.0 release, or a fix on the v3.4.x branch?

**Comment by ptabor** [comment]
I plan to finalize https://github.com/etcd-io/etcd/issues/12652 (grpc-1.32 - that is code complete) and make experimental 3.5.0-alpha.0 release. 
There is no readmap (unfortunately) for final 3.5.0 release.

**Comment by feldgendler** [comment]
@ptabor Thanks a lot for the update!
